apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-billing-config
  namespace: fiap-oficina
  labels:
    app: payment-billing-service
data:
  DB_HOST: "mysql-payment"
  DB_PORT: "3306"
  DB_NAME: "payment_db"
  DB_USERNAME: "oficina_user"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "guest"
  APP_BASE_URL: "https://api.oficina.com"
  MERCADO_PAGO_NOTIFICATION_URL: "https://api.oficina.com/api/payments/webhook"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  LOGGING_LEVEL_COM_FIAP: "INFO"
