apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-billing-service
  namespace: fiap-oficina
  labels:
    app: payment-billing-service
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-billing-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: payment-billing-service
        version: "1.0.0"
    spec:
      containers:
        - name: payment-billing-service
          image: payment-billing-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http

          envFrom:
            - configMapRef:
                name: oficina-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oficina-secrets
                  key: DB_PASSWORD
            - name: MERCADO_PAGO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: oficina-secrets
                  key: MERCADO_PAGO_ACCESS_TOKEN
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 12

      terminationGracePeriodSeconds: 30
