apiVersion: v1
kind: Service
metadata:
  name: payment-billing-service
  namespace: fiap-oficina
  labels:
    app: payment-billing-service
spec:
  type: ClusterIP
  selector:
    app: payment-billing-service
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
